built_in(!).
built_in('C'(_,_,_)).
built_in((:- _)).
built_in((?- _)).
built_in(?=(_,_)).
built_in([]).
built_in([_|_]).
built_in(\+ _).
built_in(_ is _).
built_in((_,_)).
built_in((_->_)).
built_in((_:-_)).
built_in(_:_).
built_in((_;_)).
built_in((_|_)).
built_in(_<_).
built_in(_=.._).
built_in(_=:=_).
built_in(_=<_).
built_in(_==_).
built_in(_=\=_).
built_in(_=_).
built_in(_>=_).
built_in(_>_).
built_in(_@<_).
built_in(_@=<_).
built_in(_@>=_).
built_in(_@>_).
built_in(_\==_).
built_in(_^_).
built_in(abolish(_)).
built_in(abolish(_,_)).
built_in(abort).
built_in(absolute_file_name(_,_)).
built_in(absolute_file_name(_,_,_)).
built_in(ancestors(_)).
built_in(arg(_,_,_)).
built_in(assert(_)).
built_in(assert(_,_)).
built_in(asserta(_)).
built_in(asserta(_,_)).
built_in(assertz(_)).
built_in(assertz(_,_)).
built_in(atom(_)).
built_in(atom_chars(_,_)).
built_in(atomic(_)).
built_in(bagof(_,_,_)).
built_in(block(_)).
built_in(break).
built_in(call(_)).
built_in(call_residue(_,_)).
built_in(character_count(_,_)).
built_in(clause(_,_)).
built_in(clause(_,_,_)).
built_in(close(_)).
built_in(compare(_,_,_)).
built_in(compile(_)).
built_in(consult(_)).
built_in(copy_term(_,_)).
built_in(current_atom(_)).
built_in(current_host(_)).
built_in(current_input(_)).
built_in(current_key(_,_)).
built_in(current_module(_)).
built_in(current_module(_,_)).
built_in(current_op(_,_,_)).
built_in(current_output(_)).
built_in(current_predicate(_,_)).
built_in(current_stream(_,_,_)).
built_in(debug).
built_in(debugging).
built_in(depth(_)).
built_in(dif(_,_)).
built_in(display(_)).
built_in(discontiguous(_)).
built_in(dynamic(_)).
built_in(ensure_loaded(_)).
built_in(erase(_)).
built_in(expand_term(_,_)).
built_in(extern(_)).
built_in(fail).
built_in(false).
built_in(fcompile(_)).
built_in(fileerrors).
built_in(findall(_,_,_)).
built_in(findall(_,_,_,_)).
built_in(float(_)).
built_in(flush_output(_)).
built_in(format(_,_)).
built_in(format(_,_,_)).
built_in(freeze(_,_)).
built_in(frozen(_,_)).
built_in(functor(_,_,_)).
built_in(garbage_collect).
built_in(gc).
built_in(get(_)).
built_in(get(_,_)).
built_in(get0(_)).
built_in(get0(_,_)).
built_in(ground(_)).
built_in(halt).
built_in(help).
built_in(if(_,_,_)).
built_in(incore(_)).
built_in(instance(_,_)).
built_in(integer(_)).
built_in(keysort(_,_)).
built_in(leash(_)).
built_in(length(_,_)).
built_in(library_directory(_)).
built_in(line_count(_,_)).
built_in(line_position(_,_)).
built_in(listing(_)).
built_in(listing).
built_in(load(_)).
built_in(load_foreign_files(_,_)).
built_in(maxdepth(_)).
built_in(meta_predicate(_)).
built_in(mode(_)).
built_in(module(_)).
built_in(module(_,_)).
built_in(multifile(_)).
built_in(name(_,_)).
built_in(nl(_)).
built_in(nl).
built_in(nodebug).
built_in(nofileerrors).
built_in(nogc).
built_in(nonvar(_)).
built_in(nospy(_)).
built_in(nospyall).
built_in(notrace).
built_in(number(_)).
built_in(number_chars(_,_)).
built_in(numbervars(_,_,_)).
built_in(on_exception(_,_,_)).
built_in(op(_,_,_)).
built_in(open(_,_,_)).
built_in(open_null_stream(_)).
built_in(otherwise).
built_in(phrase(_,_)).
built_in(phrase(_,_,_)).
built_in(plsys(_)).
built_in(portray_clause(_)).
built_in(portray_clause(_,_)).
built_in(predicate_property(_,_)).
built_in(prepare_foreign_files(_)).
built_in(print(_)).
built_in(print(_,_)).
built_in(profile_data(_,_,_,_)).
built_in(profile_reset(_)).
built_in(prolog_flag(_,_)).
built_in(prolog_flag(_,_,_)).
built_in(prolog_load_context(_, _)).
built_in(prompt(_,_)).
built_in(public(_)).
built_in(put(_)).
built_in(put(_,_)).
built_in(raise_exception(_)).
built_in(read(_)).
built_in(read(_,_)).
built_in(reconsult(_)).
built_in(recorda(_,_,_)).
built_in(recorded(_,_,_)).
built_in(recordz(_,_,_)).
built_in(reinitialise).
built_in(repeat).
built_in(require(_)).
built_in(restore(_)).
built_in(retract(_)).
built_in(retractall(_)).
built_in(save(_)).
built_in(save(_,_)).
built_in(save_program(_)).
built_in(see(_)).
built_in(seeing(_)).
built_in(seen).
built_in(set_input(_)).
built_in(set_output(_)).
built_in(setarg(_,_,_)).
built_in(setof(_,_,_)).
built_in(skip(_)).
built_in(skip(_,_)).
built_in(socket(_,_)).
built_in(socket_accept(_,_)).
built_in(socket_bind(_,_)).
built_in(socket_connect(_,_,_)).
built_in(socket_interrupt(_,_,_)).
built_in(socket_listen(_,_)).
built_in(socket_select(_,_,_,_,_)).
built_in(sort(_,_)).
built_in(source_file(_)).
built_in(source_file(_,_)).
built_in(spy(_)).
built_in(statistics(_,_)).
built_in(statistics).
built_in(stream_code(_,_)).
built_in(subgoal_of(_)).
built_in(tab(_)).
built_in(tab(_,_)).
built_in(tell(_)).
built_in(telling(_)).
built_in(time_out(_,_,_)).
built_in(told).
built_in(trace).
built_in(true).
built_in(ttyflush).
built_in(ttyget(_)).
built_in(ttyget0(_)).
built_in(ttynl).
built_in(ttyput(_)).
built_in(ttyskip(_)).
built_in(ttytab(_)).
built_in(undo(_)).
built_in(unix(_)).
built_in(unknown(_,_)).
built_in(use_module(_)).
built_in(use_module(_,_)).
built_in(use_module(_,_,_)).
built_in(var(_)).
built_in(version(_)).
built_in(version).
built_in(when(_,_)).
built_in(write(_)).
built_in(write(_,_)).
built_in(write_canonical(_)).
built_in(write_canonical(_,_)).
built_in(writeq(_)).
built_in(writeq(_,_)).
built_in(initialization(_)).
