#!/bin/csh -f
# Request a patch tape from the SWI mail-server
#
# To upgrade SWI-Prolog to the latest version, you may wish to execute this
# shell script.  It sends a mail to the mail upgrade server at swi.  This
# server will compute a patch file from your version to the current version
# and resend the patch file as a bundle of mail-messages to you.

set stamp=`cat STAMP`
set version=`cat VERSION`

mail upgrade@swi.psy.uva.nl << _EOM_
Module:          pl
Time Stamp:      $stamp
Current Version: $version
Request Version: latest
_EOM_
