#!/bin/bash

# Generate old-style ChangeLog files from the GIT log. Ultimately we may
# wish to insert this into ChangeLog

footer=false
printdate=true
directory=.
since=
until=
modules=true
quiet=false
moduleoptions=
[ -z "$wiki"  ] && wiki=false
[ -z "$level" ] && level=+

export wiki level

done=false
while [ $done = false ]; do
    case "$1" in
	--footer)
		footer=true
		shift
		;;
	--nodate)
		printdate=false
		shift
		moduleoptions+="--nodate"
		;;
	--quiet)
		quiet=true
		shift
		;;
	--wiki)
		wiki=true
		shift
		;;
	--nomodules)
		modules=false
		shift
		;;
	--dir=*)
		directory="`echo $1 | sed 's/--dir=//'`"
		shift
		modules=false
		;;
	--since=*)
		since="`echo $1 | sed 's/--since=//'`"
		shift
		;;
	--until=*)
		until="`echo $1 | sed 's/--until=//'`"
		shift
		;;
	*)	done=true
		;;
    esac
done

tag="$1"

if [ -z "$tag" -a -z "$since" ]; then
   echo "Usage: `basename $0` option ... [version] [path ...]"
   echo "Options:"
   echo "    --footer"
   echo "    --nodate"
   echo "    --nomodules"
   echo "    --since=<date>"
   echo "    --dir=<dir>"
   exit 1
fi

# Ensure case-sensitive matching
LANG=C

case "$tag" in
   [0-9].[0-9]*.[0-9]*..[0-9].[0-9]*.[0-9]*)
	vfrom="$(echo $tag | sed 's/\.\..*//')"
	vto="$(echo $tag | sed 's/.*\.\.//')"
	;;
   V[0-9].[0-9]*.[0-9]*..V[0-9].[0-9]*.[0-9]*)
	vfrom="$(echo $tag | sed -e s/V//g -e 's/\.\..*//')"
	vto="$(echo $tag | sed -e s/V//g -e 's/.*\.\.//')"
	;;
   [0-9].[0-9]*.[0-9]*)
        vfrom="$tag"
	vto=
	;;
   V[0-9].[0-9]*.[0-9]*)
        vfrom="$(echo $tag | sed s/V//)"
	vto=
	;;
esac

# --no-color is just a no-op option
optx=--no-color
if [ ! -z "$since" ]; then
  opt="--since=$since"
  if [ ! -z "$until" ]; then
    optx="--until=$until"
  fi
else
  shift
  if [ -z "$vto" ]; then
    opt="V$vfrom.."
  else
    opt="V$vfrom..V$vto"
  fi
fi

cd $directory

if [ "$quiet" = true ]; then
  git log "$opt" --pretty=format:"PATCH[%ad]%n%s%n%b" $* | grep -q '^[A-Z][A-Z]*:'
  exit $?
fi

header ()
{ hdr="$*"

  if [ "$wiki" = true ]; then
    echo ---$level $hdr
  else
    hdr="$*"
    eq=`echo $hdr | sed 's/./=/g'`
    echo $eq
    echo $hdr
    echo $eq
  fi

  echo
}

(
if [ "$directory" = "." ]; then
  if [ -z "$vto" ]; then
    header "SWI-Prolog Changelog since version $vfrom"
  else
    header "SWI-Prolog Changelog from version $vfrom to $vto"
  fi
else
  header "Package `basename $directory`"
fi

git log "$opt" "$optx" --pretty=format:"PATCH[%ad]%n%s%n%b" $* | awk '
BEGIN		{ doprint="false";
		  dateprinted="";
		}
/^PATCH[[]/	{ date="["  $2 " " $3 " " $5 "]";
		  doprint="false";
		  next;
	        }
/^[A-Z][A-Z]*:/	{ if ( dateprinted != date )
		  { if ( "'$printdate'" == "true" )
		    { printf("%s\n\n", date);
		    }
		    dateprinted = date;
		  }
		  printf(" * %s\n", $0);
		  doprint="true";
		  next;
		}
/.*/		{ if ( doprint == "true" )
		  { if ( $0 != "<unknown>" )
		    { printf("   %s\n", $0);
		    } else
		    { printf("\n");
		    }
		  }
		  next;
		}
' ) | fmt -ut

# Include submodules

if [ "$modules" = true ]; then
  level="$level+"

  if [ -z "$since" ]; then
    since="'"$(git show --pretty=format:%cd "V$vfrom^{commit}" | head -1)"'"
  fi
  if [ -z "$until" -a ! -z "$vto" ]; then
    until="'"$(git show --pretty=format:%cd "V$vto^{commit}" | head -1)"'"
  fi

  subopts=--since="$since"
  if [ ! -z "$since" ]; then
    subopts="$subopts --until=$until"
  fi

  echo

  for d in `git submodule -q foreach pwd`; do
    if $0 --dir="$d" "$subopts" --quiet; then
      echo
      $0 --dir="$d" "$subopts" $moduleoptions
#   else
#     echo "Package `basename $d`: no changes"
    fi
  done
fi

if [ "$footer" = true ]; then
   header VERSION $tag
fi
