.TH SWI 1 "August 10 1995"
.SH NAME
chpl \- Change header of SWI-Prolog saved-states
.SH SYNOPSIS
.BR chpl
.BI "\-e" " emulator" " [\|" "\-o" " outputfile" "\|]"
.BI "state"
.br
.BR chpl
.BI "\-x" " [\|" "\-o" " outputfile" "\|]" " state"
.br
.BR chpl
.BI "\-h" " header" " [\|" "\-o" " outputfile" "\|]"
.BI "state"
.br
.SH DESCRIPTION
The utility
.BI chpl
changes the header of a SWI-Prolog boot file or SWI-Prolog runtime
program.  A SWI-Prolog program is a
.BI /bin/sh
script.  The last line of this script normally exec's the SWI-Prolog
emulator.  The first form of this command changes the path to the
emulator of the script to be the specified emulator.  The second
form extracts the entire header to the named output file or the
standard output.  The third form replaces the header of
.BI state
with the contents of
.BI header.
If
.BI header
is `-', the standard input will be used as header script.
.SS Options
.TP
.BI \-e " emulator"
Specifies a path to the emulator.  This should be a SWI-Prolog executable.
The path must be absolute.
.TP
.BI \-o " outfile"
Name of the output file.  When omited, the state is changed in-place.  If
the output file is omited with the
.BI \-x
flag the header is extracted to standard output.
.TP
.BI \-h " header"
Name of the file from which to extract the new header.  If its value is
a single -, standard input is used.
.SH "SEE ALSO"
Jan Wielemaker
.I pl(1)
.I SWI-Prolog 2.1 Reference Manual,
University of Amsterdam, Dept. of Social Science and Informatics (SWI).
.SH COPYRIGHT
Copyright (C) 1991-1995, Jan Wielemaker
.SH AUTHOR
Jan Wielemaker
