#!/bin/csh -f
# Create a stand alone executable of SWI-Prolog

set pl=./pl

switch( $#argv )
	case 0:
		set bin=/usr/local/bin/$pl
		breaksw
	case 1:
		set pl=$1
		set bin=/usr/local/bin/$pl
		breaksw
	case 2:
		set pl=$1
		set bin=$2
		breaksw
	default:
		echo "Usage: dump [sys] [executable]"
		exit 1
endsw

$pl -f none -B << _EOS_
save_program('$bin',
	[ goal		= '''\$welcome'''
	, toplevel	= prolog
	, init_file	= '.plrc'
	]).	
forall(library_directory(X),
       (exists_directory(X) -> make_library_index(X) ; true)).
halt.
_EOS_
