#!/bin/sh
# Author: Stepan Kasal <kasal@suse.cz>
# Version: 0.1
#	this shell script is public domain ;-)
# Modified: Thu Feb 17 2000 (JW)
#	Avoid use of ln -sf (GNU specific)

check_path() {
  if ! echo $1|grep -q ^/ ; then
	echo "Error: $1 isn't absolute path" >&2
	exit 1
  fi
}

compare() {
  test $# = 4 && test "$1" = "$3" && from=$2 && to=$4
}

if test $# != 2 ; then
  echo "usage:  $0 from to
	creates relative symbolic link from \$1 to \$2" >&2
  exit 1
fi

from=$1
to=$2
abs_to=$2

check_path $from
check_path $to

test -d $to && to=$to/`echo $from|sed 's,.*/,,'`
from=`echo $from|sed 's,/,,;s,/\+,/,g'`
to=`echo $to|sed 's,/,,;s,/\+,/,g'`

while compare `echo $from|sed "s,/, ,"` `echo $to|sed "s,/, ,"`
do test a = a
done

relf="`echo $to|sed 's,[^/]\+/,../,g;s,[^/]\+$,,'`$from"

rm -f $relf
ln -s $relf $abs_to
