name: swi-prolog
# Should be core20 to avoid fontconfig warnings, but Qt is broken on
# core20
base: core18
adopt-info: swi-prolog
#icon: packages/swipl-win/swipl.png
license: 'BSD-2-Clause'
summary: ISO/Edinburgh-style Prolog implementation
description: |
  SWI-Prolog is a fast and powerful ISO/Edinburgh-style Prolog compiler with a
  rich set of built-in predicates. It offers a fast, robust and small
  environment which enables substantial applications to be developed with it.
  .
  SWI-Prolog additionally offers:
  .
  * A powerful module system
  * Garbage collection
  * Unicode character set handling
  * Unbounted integer and rational number arithmetic
  * Multithreading support
  * A powerful C/C++ interface
  * GNU Readline interface
  .

apps:
  swipl:
    command: $SNAP/usr/lib/swipl/bin/x86_64-linux/swipl
  swipl-win:
    command: bin/desktop-launch $SNAP/usr/lib/swipl/bin/x86_64-linux/swipl-win

grade: stable
confinement: classic
compression: lzo    # should make startup nearly as fast as regular executables

plugs:
  graphics-core20:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core20

layout:
  /usr/share/libdrm:  # Needed by mesa-core20 on AMD GPUs
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:  # Used by mesa-core20 for app specific workarounds
    bind: $SNAP/graphics/drirc.d

environment:
  LD_LIBRARY_PATH:    $SNAP/graphics/lib
  LIBGL_DRIVERS_PATH: $SNAP/graphics/dri
  LIBVA_DRIVERS_PATH: $SNAP/graphics/dri
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/graphics/glvnd/egl_vendor.d

parts:
  swi-prolog:
    source: https://github.com/SWI-Prolog/swipl-devel.git
    after:
      - qt5
    source-type: git
    source-depth: 1
    plugin: cmake
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(cat VERSION)"
    override-build: |
      # Custom build process to enable PGO build
      mkdir -p $SNAPCRAFT_PART_SRC/build
      cd $SNAPCRAFT_PART_SRC/build
      cmake -DCMAKE_BUILD_TYPE=PGO \
      -DSWIPL_PACKAGES_JAVA=OFF \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DSWIPL_INSTALL_IN_LIB=ON \
      -G Ninja ..
      ninja
      DESTDIR=$SNAPCRAFT_PART_INSTALL ninja install
    stage-packages:
      # Remove packages available in the kde base
      - ca-certificates
      - libarchive13
      - libdb5.3
      - libedit2
      - libfontconfig1
      - libglu1-mesa
      - libgmp10
      - libjpeg8
      - libssl1.1
      - libx11-6
      - libossp-uuid16
      - libpcre2-8-0
      - libserd-0-0
      - libxft2
      - libxpm4
      - libxt6
      - odbc-postgresql
      - tdsodbc
      - libtcmalloc-minimal4
      - unixodbc
    build-packages:
      - libarchive-dev
      - libdb-dev
      - libedit-dev
      - libgeos++-dev
      - libgmp-dev
      - libice-dev
      - libjpeg-dev
      - libossp-uuid-dev
      - libpcre2-dev
      - libraptor2-dev
      - libreadline-dev
      - libserd-dev
      - libsqlite3-dev
      - libssl-dev
      - libxext-dev
      - libxft-dev
      - libxinerama-dev
      - libxpm-dev
      - libxt-dev
      - ninja-build
      - unixodbc-dev
      - zlib1g-dev
      - libyaml-dev
      - libglvnd-dev
      - libgoogle-perftools-dev
  qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - locales-all
  cleanup:
    after: [swi-prolog]
    plugin: nil
    build-snaps: [ mesa-core20 ]
    override-prime: |
      set -eux
      cd /snap/mesa-core20/current/egl/lib
      find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/{} \;
      rm -fr "$SNAPCRAFT_PRIME/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri"
      for CRUFT in bug drirc.d glvnd libdrm lintian man; do
        rm -rf "$SNAPCRAFT_PRIME/usr/share/$CRUFT"
      done
